// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Columbia.DslPackage.CodeGenerators
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EntityCodeGenerator : Columbia.DslPackage.CodeGenerators.Base.CodeGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.ComponentModel.Dat" +
                    "aAnnotations;\r\nusing System.ComponentModel.DataAnnotations.Schema;\r\n");
            
            #line 10 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

if(Entity.IsAuditable)
{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 14 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Entity));
            
            #line default
            #line hidden
            this.Write(".Base;\r\n");
            
            #line 15 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

}

            
            #line default
            #line hidden
            
            #line 18 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

var relatedEntities = DomainModel.Entities.Where(x => x.EntityProperties.Any(p => p.Type == Entity.Name));

            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 22 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Entity));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 24 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

if(Entity != null)
{

            
            #line default
            #line hidden
            
            #line 28 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

	PushIndent(DefautIndent);

            
            #line default
            #line hidden
            this.Write("public class ");
            
            #line 31 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            
            #line 31 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.IsAuditable ? " : SystemEntity" : string.Empty));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 33 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

	if(relatedEntities.Any())
	{
		PushIndent(DefautIndent);

            
            #line default
            #line hidden
            this.Write("public ");
            
            #line 38 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n{\r\n");
            
            #line 40 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

		PushIndent(DefautIndent);

		foreach(var relatedEntity in relatedEntities)
		{

            
            #line default
            #line hidden
            
            #line 46 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntity.Name));
            
            #line default
            #line hidden
            this.Write("s = new HashSet<");
            
            #line 46 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntity.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 47 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

		}

		PopIndent();

            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            
            #line 54 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
	
		PopIndent();
	}
	
	PushIndent(DefautIndent);

	foreach (var primitiveProperty in Entity.PrimitiveProperties.Where(x => x.IsPrimaryKey))
	{

            
            #line default
            #line hidden
            this.Write("[Key]\r\npublic ");
            
            #line 64 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primitiveProperty.Type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 64 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primitiveProperty.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 65 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

	}

	PopIndent();

            
            #line default
            #line hidden
            
            #line 70 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

	PushIndent(DefautIndent);

	foreach (var entityProperty in Entity.EntityProperties)
	{
		var relatedEntity = DomainModel.Entities.FirstOrDefault(x => x.Name == entityProperty.Type);
		var relatedEntityKey = relatedEntity != null ? relatedEntity.PrimitiveProperties.FirstOrDefault(x => x.IsPrimaryKey) : null;

            
            #line default
            #line hidden
            
            #line 78 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

		if(relatedEntityKey != null)
		{

            
            #line default
            #line hidden
            this.Write("[ForeignKey(\"");
            
            #line 82 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            
            #line 82 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntityKey.Name));
            
            #line default
            #line hidden
            this.Write("\")]\r\n");
            
            #line 83 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("public virtual ");
            
            #line 86 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 86 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; } = null!;\r\n");
            
            #line 87 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

		if(relatedEntityKey != null)
		{

            
            #line default
            #line hidden
            this.Write("public ");
            
            #line 91 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntityKey.Type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 91 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            
            #line 91 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntityKey.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 92 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

		}

            
            #line default
            #line hidden
            
            #line 95 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

	}

	PopIndent();

            
            #line default
            #line hidden
            
            #line 100 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

	PushIndent(DefautIndent);

	foreach (var primitiveProperty in Entity.PrimitiveProperties.Where(x => !x.IsPrimaryKey))
	{

            
            #line default
            #line hidden
            this.Write("public ");
            
            #line 106 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primitiveProperty.Type));
            
            #line default
            #line hidden
            
            #line 106 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primitiveProperty.Nullable ? "?" : string.Empty));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 106 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primitiveProperty.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }");
            
            #line 106 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primitiveProperty.Nullable ? " = null!;" : string.Empty));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 107 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

	}

	PopIndent();

	if(relatedEntities.Any())
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 116 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

		PushIndent(DefautIndent);

		foreach(var relatedEntity in relatedEntities)
		{

            
            #line default
            #line hidden
            this.Write("public virtual ICollection<");
            
            #line 122 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntity.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 122 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntity.Name));
            
            #line default
            #line hidden
            this.Write("s { get; set; }\r\n");
            
            #line 123 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

		}

		PopIndent();
	}

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 130 "D:\Projects\Columbia\DslPackage\CodeGenerators\Entity\Templates\EntityCodeGenerator.tt"

ClearIndent();
}

            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
