// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Columbia.DslPackage.CodeGenerators
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CreateCommandHandlerCodeGenerator : Columbia.DslPackage.CodeGenerators.Base.CodeGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"

    var module = !string.IsNullOrEmpty(Entity.Module) ? Entity.Module : Entity.Name;

            
            #line default
            #line hidden
            this.Write("using AutoMapper;\r\nusing ");
            
            #line 10 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Domain));
            
            #line default
            #line hidden
            this.Write(".Commands.Base;\r\nusing ");
            
            #line 11 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.RepositoryAbstractions));
            
            #line default
            #line hidden
            this.Write(".Base;\r\nusing ");
            
            #line 12 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.RepositoryAbstractions));
            
            #line default
            #line hidden
            this.Write(".Transactions;\r\nusing ");
            
            #line 13 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Dto));
            
            #line default
            #line hidden
            this.Write(".Base;\r\nusing ");
            
            #line 14 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Dto));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 14 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 16 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Domain));
            
            #line default
            #line hidden
            this.Write(".Commands.");
            
            #line 16 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class Create");
            
            #line 18 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("CommandHandler(\r\n        IUnitOfWork unitOfWork,\r\n        IMapper mapper,\r\n      " +
                    "  Create");
            
            #line 21 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("CommandValidator validator,\r\n        IRepository<Entity.");
            
            #line 22 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 22 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Repository\r\n    ) : CommandHandlerBase<Create");
            
            #line 23 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Command, Get");
            
            #line 23 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>(unitOfWork, mapper, validator)\r\n    {\r\n        public override async Task<Re" +
                    "sponseDto<Get");
            
            #line 25 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>> HandleCommand(Create");
            
            #line 25 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Command request, CancellationToken cancellationToken)\r\n        {\r\n            var" +
                    " response = new ResponseDto<Get");
            
            #line 27 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>();\r\n            var ");
            
            #line 28 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write(" = _mapper?.Map<Entity.");
            
            #line 28 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(">(request.CreateDto);\r\n\r\n            if (");
            
            #line 30 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n            {\r\n                await ");
            
            #line 32 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Repository.AddAsync(");
            
            #line 32 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write(");\r\n                await ");
            
            #line 33 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Repository.SaveAsync();\r\n            }\r\n\r\n            var ");
            
            #line 36 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Dto = _mapper?.Map<Get");
            
            #line 36 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>(");
            
            #line 36 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write(");\r\n            if (");
            
            #line 37 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Dto != null) response.UpdateData(");
            
            #line 37 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\CreateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Dto);\r\n\r\n            response.AddOkResult(Resources.Common.CreateSuccessMessage);" +
                    "\r\n\r\n            return await Task.FromResult(response);\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
