// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Columbia.DslPackage.CodeGenerators
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class UpdateCommandHandlerCodeGenerator : Columbia.DslPackage.CodeGenerators.Base.CodeGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"

    var module = !string.IsNullOrEmpty(Entity.Module) ? Entity.Module : Entity.Name;

            
            #line default
            #line hidden
            this.Write("using AutoMapper;\r\nusing ");
            
            #line 10 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Domain));
            
            #line default
            #line hidden
            this.Write(".Commands.Base;\r\nusing ");
            
            #line 11 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.RepositoryAbstractions));
            
            #line default
            #line hidden
            this.Write(".Base;\r\nusing ");
            
            #line 12 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.RepositoryAbstractions));
            
            #line default
            #line hidden
            this.Write(".Transactions;\r\nusing ");
            
            #line 13 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Dto));
            
            #line default
            #line hidden
            this.Write(".Base;\r\nusing ");
            
            #line 14 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Dto));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 14 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 16 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Domain));
            
            #line default
            #line hidden
            this.Write(".Commands.");
            
            #line 16 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class Update");
            
            #line 18 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("CommandHandler : CommandHandlerBase<Update");
            
            #line 18 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Command, Get");
            
            #line 18 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>\r\n    {\r\n        private readonly IRepository<Entity.");
            
            #line 20 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("> _");
            
            #line 20 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Repository;\r\n\r\n        public Update");
            
            #line 22 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("CommandHandler(\r\n            IUnitOfWork unitOfWork,\r\n            IMapper mapper," +
                    "\r\n            Update");
            
            #line 25 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("CommandValidator validator,\r\n            IRepository<Entity.");
            
            #line 26 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 26 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Repository\r\n        ) : base(unitOfWork, mapper, validator)\r\n        {\r\n         " +
                    "   _");
            
            #line 29 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Repository = ");
            
            #line 29 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Repository;\r\n        }\r\n\r\n        public override async Task<ResponseDto<Get");
            
            #line 32 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>> HandleCommand(Update");
            
            #line 32 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Command request, CancellationToken cancellationToken)\r\n        {\r\n            var" +
                    " response = new ResponseDto<Get");
            
            #line 34 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>();\r\n\r\n");
            
            #line 36 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"

	var keyProperty = Entity.PrimitiveProperties.FirstOrDefault(x => x.IsPrimaryKey);
	if (keyProperty != null)
	{

            
            #line default
            #line hidden
            this.Write("            var ");
            
            #line 41 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write(" = await _");
            
            #line 41 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Repository.GetByAsync(x => x.");
            
            #line 41 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyProperty.Name));
            
            #line default
            #line hidden
            this.Write(" == request.UpdateDto.");
            
            #line 41 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyProperty.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n            if (");
            
            #line 42 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n            {\r\n                _mapper?.Map(request.UpdateDto, ");
            
            #line 44 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write(");\r\n                await _");
            
            #line 45 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Repository.UpdateAsync(");
            
            #line 45 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write(");\r\n            }\r\n\r\n            var ");
            
            #line 48 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Dto = _mapper?.Map<Get");
            
            #line 48 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>(");
            
            #line 48 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write(");\r\n            if (");
            
            #line 49 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Dto != null) response.UpdateData(");
            
            #line 49 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerFirst(Entity.Name)));
            
            #line default
            #line hidden
            this.Write("Dto);\r\n\r\n");
            
            #line 51 "D:\Projects\Columbia\DslPackage\CodeGenerators\Domain\Templates\UpdateCommandHandlerCodeGenerator.tt"

    }

            
            #line default
            #line hidden
            this.Write("            response.AddOkResult(Resources.Common.UpdateSuccessMessage);\r\n\r\n     " +
                    "       return await Task.FromResult(response);\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
