// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Columbia.DslPackage.CodeGenerators
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ApplicationAbstractionsCodeGenerator : Columbia.DslPackage.CodeGenerators.Base.CodeGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"

    var module = !string.IsNullOrEmpty(Entity.Module) ? Entity.Module : Entity.Name;
	var keyProperty = Entity.PrimitiveProperties.FirstOrDefault(x => x.IsPrimaryKey);

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 10 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Dto));
            
            #line default
            #line hidden
            this.Write(".Base;\r\nusing ");
            
            #line 11 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Dto));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 11 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 13 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.ApplicationAbstractions));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public interface I");
            
            #line 15 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module));
            
            #line default
            #line hidden
            this.Write("Application\r\n    {\r\n        Task<ResponseDto<Get");
            
            #line 17 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>> Create(Create");
            
            #line 17 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto createDto);\r\n        Task<ResponseDto<Get");
            
            #line 18 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>> Update(Update");
            
            #line 18 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto updateDto);\r\n        Task<ResponseDto> Delete(");
            
            #line 19 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyProperty != null ? keyProperty.Type + " " + LowerFirst(keyProperty.Name) : string.Empty));
            
            #line default
            #line hidden
            this.Write(");\r\n        Task<ResponseDto<Get");
            
            #line 20 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>> Get(");
            
            #line 20 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyProperty != null ? keyProperty.Type + " " + LowerFirst(keyProperty.Name) : string.Empty));
            
            #line default
            #line hidden
            this.Write(");\r\n        Task<ResponseDto<IEnumerable<List");
            
            #line 21 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>>> List();\r\n        Task<ResponseDto<SearchResultDto<Search");
            
            #line 22 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>>> Search(SearchParamsDto<Search");
            
            #line 22 "D:\Projects\Columbia\DslPackage\CodeGenerators\ApplicationAbstractions\Templates\ApplicationAbstractionsCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterDto> searchParams);\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
