// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Columbia.DslPackage.CodeGenerators
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ApplicationCodeGenerator : Columbia.DslPackage.CodeGenerators.Base.CodeGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"

    var entitySuffix = !string.IsNullOrEmpty(Entity.Module) && Entity.Module != Entity.Name ? Entity.Name : string.Empty;
    var module = !string.IsNullOrEmpty(Entity.Module) ? Entity.Module : Entity.Name;
	var keyProperty = Entity.PrimitiveProperties.FirstOrDefault(x => x.IsPrimaryKey);

            
            #line default
            #line hidden
            this.Write("using MediatR;\r\nusing ");
            
            #line 12 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.ApplicationAbstractions));
            
            #line default
            #line hidden
            this.Write(";\r\nusing ");
            
            #line 13 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Application));
            
            #line default
            #line hidden
            this.Write(".Base;\r\nusing ");
            
            #line 14 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Domain));
            
            #line default
            #line hidden
            this.Write(".Commands.");
            
            #line 14 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module));
            
            #line default
            #line hidden
            this.Write(";\r\nusing ");
            
            #line 15 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Domain));
            
            #line default
            #line hidden
            this.Write(".Queries.");
            
            #line 15 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module));
            
            #line default
            #line hidden
            this.Write(";\r\nusing ");
            
            #line 16 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Dto));
            
            #line default
            #line hidden
            this.Write(".Base;\r\nusing ");
            
            #line 17 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Dto));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 17 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 19 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DomainModel.Application));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 21 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module));
            
            #line default
            #line hidden
            this.Write("Application : ApplicationBase, I");
            
            #line 21 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module));
            
            #line default
            #line hidden
            this.Write("Application\r\n    {\r\n        public ");
            
            #line 23 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module));
            
            #line default
            #line hidden
            this.Write("Application(IMediator mediator) : base(mediator)\r\n        {\r\n\r\n        }\r\n\r\n     " +
                    "   public async Task<ResponseDto<Get");
            
            #line 28 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>> Create");
            
            #line 28 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySuffix));
            
            #line default
            #line hidden
            this.Write("(Create");
            
            #line 28 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto createDto)\r\n            => await _mediator.Send(new Create");
            
            #line 29 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Command(createDto));\r\n\r\n        public async Task<ResponseDto<Get");
            
            #line 31 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>> Update");
            
            #line 31 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySuffix));
            
            #line default
            #line hidden
            this.Write("(Update");
            
            #line 31 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto updateDto)\r\n            => await _mediator.Send(new Update");
            
            #line 32 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Command(updateDto));\r\n\r\n        public async Task<ResponseDto> Delete");
            
            #line 34 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySuffix));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 34 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyProperty != null ? keyProperty.Type + " " + LowerFirst(keyProperty.Name) : string.Empty));
            
            #line default
            #line hidden
            this.Write(")\r\n            => await _mediator.Send(new Delete");
            
            #line 35 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Command(");
            
            #line 35 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyProperty != null ? LowerFirst(keyProperty.Name) : string.Empty));
            
            #line default
            #line hidden
            this.Write("));\r\n\r\n        public async Task<ResponseDto<Get");
            
            #line 37 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>> Get");
            
            #line 37 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySuffix));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 37 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyProperty != null ? keyProperty.Type + " " + LowerFirst(keyProperty.Name) : string.Empty));
            
            #line default
            #line hidden
            this.Write(")\r\n            => await _mediator.Send(new Get");
            
            #line 38 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Query(");
            
            #line 38 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyProperty != null ? LowerFirst(keyProperty.Name) : string.Empty));
            
            #line default
            #line hidden
            this.Write("));\r\n\r\n        public async Task<ResponseDto<IEnumerable<List");
            
            #line 40 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>>> List");
            
            #line 40 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySuffix));
            
            #line default
            #line hidden
            this.Write("()\r\n            => await _mediator.Send(new List");
            
            #line 41 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Query());\r\n\r\n        public async Task<ResponseDto<SearchResultDto<Search");
            
            #line 43 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Dto>>> Search");
            
            #line 43 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySuffix));
            
            #line default
            #line hidden
            this.Write("(SearchParamsDto<Search");
            
            #line 43 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterDto> searchParams)\r\n            => await _mediator.Send(new Search");
            
            #line 44 "D:\Projects\Columbia\DslPackage\CodeGenerators\Application\Templates\ApplicationCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Query(searchParams));\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
