//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Columbia.Dsl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TypeConverters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TypeConverters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Columbia.Dsl.Resources.TypeConverters", typeof(TypeConverters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool.
        /// </summary>
        internal static string PrimitiveType_Boolean {
            get {
                return ResourceManager.GetString("PrimitiveType_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte.
        /// </summary>
        internal static string PrimitiveType_Byte {
            get {
                return ResourceManager.GetString("PrimitiveType_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte[].
        /// </summary>
        internal static string PrimitiveType_ByteArray {
            get {
                return ResourceManager.GetString("PrimitiveType_ByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to char.
        /// </summary>
        internal static string PrimitiveType_Char {
            get {
                return ResourceManager.GetString("PrimitiveType_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string PrimitiveType_DateTime {
            get {
                return ResourceManager.GetString("PrimitiveType_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTimeOffset.
        /// </summary>
        internal static string PrimitiveType_DateTimeOffest {
            get {
                return ResourceManager.GetString("PrimitiveType_DateTimeOffest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decimal.
        /// </summary>
        internal static string PrimitiveType_Decimal {
            get {
                return ResourceManager.GetString("PrimitiveType_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double.
        /// </summary>
        internal static string PrimitiveType_Double {
            get {
                return ResourceManager.GetString("PrimitiveType_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        internal static string PrimitiveType_Guid {
            get {
                return ResourceManager.GetString("PrimitiveType_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to short.
        /// </summary>
        internal static string PrimitiveType_Int16 {
            get {
                return ResourceManager.GetString("PrimitiveType_Int16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int.
        /// </summary>
        internal static string PrimitiveType_Int32 {
            get {
                return ResourceManager.GetString("PrimitiveType_Int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to long.
        /// </summary>
        internal static string PrimitiveType_Int64 {
            get {
                return ResourceManager.GetString("PrimitiveType_Int64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sbyte.
        /// </summary>
        internal static string PrimitiveType_SByte {
            get {
                return ResourceManager.GetString("PrimitiveType_SByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sbyte[].
        /// </summary>
        internal static string PrimitiveType_SByteArray {
            get {
                return ResourceManager.GetString("PrimitiveType_SByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float.
        /// </summary>
        internal static string PrimitiveType_Single {
            get {
                return ResourceManager.GetString("PrimitiveType_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string PrimitiveType_String {
            get {
                return ResourceManager.GetString("PrimitiveType_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ushort.
        /// </summary>
        internal static string PrimitiveType_UInt16 {
            get {
                return ResourceManager.GetString("PrimitiveType_UInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uint.
        /// </summary>
        internal static string PrimitiveType_UInt32 {
            get {
                return ResourceManager.GetString("PrimitiveType_UInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ulong.
        /// </summary>
        internal static string PrimitiveType_UInt64 {
            get {
                return ResourceManager.GetString("PrimitiveType_UInt64", resourceCulture);
            }
        }
    }
}
